language: go

go:
  - 1.4

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/hailiang/goveralls
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/axw/gocov/gocov
  #- go get code.google.com/p/gomock/gomock
  #- go get github.com/qur/withmock
  #- PATH=$PATH:$HOME/gopath/bin withmock go test -covermode=count -coverprofile="$(pwd)/profile.cov" secstring_mocks_test.go secstring.go
  - PATH=$PATH:$HOME/gopath/bin go test -covermode=count -coverprofile="$(pwd)/profile.cov" secstring_test.go secstring.go
  #- sed -i -e 's:command-line-arguments:github.com/worr/secstring:' profile.cov
  #- sed -i -e 's:command-line-arguments:github.com/worr/secstring:' profile2.cov
  #- $HOME/gopath/bin/gocov convert profile.cov profile2.cov > profile.json
  - $HOME/gopath/bin/gocov convert profile.cov > profile.json
  - $HOME/gopath/bin/goveralls -gocovdata=profile.json -service=travis-ci
